export const bahasaIsyaratImages = {
  a: require('../../assets/images/games/bahasaisyarat/A.png'),
  b: require('../../assets/images/games/bahasaisyarat/B.png'),
  c: require('../../assets/images/games/bahasaisyarat/C.png'),
  d: require('../../assets/images/games/bahasaisyarat/D.png'),
  e: require('../../assets/images/games/bahasaisyarat/E.png'),
  f: require('../../assets/images/games/bahasaisyarat/F.png'),
  g: require('../../assets/images/games/bahasaisyarat/G.png'),
  h: require('../../assets/images/games/bahasaisyarat/H.png'),
  i: require('../../assets/images/games/bahasaisyarat/I.png'),
  j: require('../../assets/images/games/bahasaisyarat/J.png'),
  k: require('../../assets/images/games/bahasaisyarat/K.png'),
  l: require('../../assets/images/games/bahasaisyarat/L.png'),
  m: require('../../assets/images/games/bahasaisyarat/M.png'),
  n: require('../../assets/images/games/bahasaisyarat/N.png'),
  o: require('../../assets/images/games/bahasaisyarat/O.png'),
  p: require('../../assets/images/games/bahasaisyarat/P.png'),
  q: require('../../assets/images/games/bahasaisyarat/Q.png'),
  r: require('../../assets/images/games/bahasaisyarat/R.png'),
  s: require('../../assets/images/games/bahasaisyarat/S.png'),
  t: require('../../assets/images/games/bahasaisyarat/T.png'),
  u: require('../../assets/images/games/bahasaisyarat/U.png'),
  v: require('../../assets/images/games/bahasaisyarat/V.png'),
  w: require('../../assets/images/games/bahasaisyarat/W.png'),
  x: require('../../assets/images/games/bahasaisyarat/X.png'),
  y: require('../../assets/images/games/bahasaisyarat/Y.png'),
  z: require('../../assets/images/games/bahasaisyarat/Z.png'),
};