/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/splash`; params?: Router.UnknownInputParams; } | { pathname: `/guru`; params?: Router.UnknownInputParams; } | { pathname: `/guru/nilaiSiswa`; params?: Router.UnknownInputParams; } | { pathname: `/guru/profile`; params?: Router.UnknownInputParams; } | { pathname: `/guru/upload`; params?: Router.UnknownInputParams; } | { pathname: `/siswa`; params?: Router.UnknownInputParams; } | { pathname: `/siswa/game`; params?: Router.UnknownInputParams; } | { pathname: `/siswa/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/siswa/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/guru`; params?: Router.UnknownOutputParams; } | { pathname: `/guru/nilaiSiswa`; params?: Router.UnknownOutputParams; } | { pathname: `/guru/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/guru/upload`; params?: Router.UnknownOutputParams; } | { pathname: `/siswa`; params?: Router.UnknownOutputParams; } | { pathname: `/siswa/game`; params?: Router.UnknownOutputParams; } | { pathname: `/siswa/leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/siswa/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/admin`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/splash${`?${string}` | `#${string}` | ''}` | `/guru${`?${string}` | `#${string}` | ''}` | `/guru/nilaiSiswa${`?${string}` | `#${string}` | ''}` | `/guru/profile${`?${string}` | `#${string}` | ''}` | `/guru/upload${`?${string}` | `#${string}` | ''}` | `/siswa${`?${string}` | `#${string}` | ''}` | `/siswa/game${`?${string}` | `#${string}` | ''}` | `/siswa/leaderboard${`?${string}` | `#${string}` | ''}` | `/siswa/profile${`?${string}` | `#${string}` | ''}` | `/admin${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/splash`; params?: Router.UnknownInputParams; } | { pathname: `/guru`; params?: Router.UnknownInputParams; } | { pathname: `/guru/nilaiSiswa`; params?: Router.UnknownInputParams; } | { pathname: `/guru/profile`; params?: Router.UnknownInputParams; } | { pathname: `/guru/upload`; params?: Router.UnknownInputParams; } | { pathname: `/siswa`; params?: Router.UnknownInputParams; } | { pathname: `/siswa/game`; params?: Router.UnknownInputParams; } | { pathname: `/siswa/leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/siswa/profile`; params?: Router.UnknownInputParams; } | { pathname: `/admin`; params?: Router.UnknownInputParams; };
    }
  }
}
